name: Increment build-version

on:
  pull_request:
    branches: [ develop ]

jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ssh-key: ${{ secrets.DEPLOY_KEY }}

      - name: Configure Git
        run: |
          git config --global user.name "QuantraxNET"
          git config --global user.email "github@quantrax.net"

      - name: Extract branch name
        id: extract_branch
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT

      - name: Pull repository
        run: git fetch origin ${{ steps.extract_branch.outputs.branch }}

      - name: Bump Version
        id: bump_version
        run: |
          CURRENT_VERSION=$(grep -oP '(?<=version = ").*(?=")' build.gradle.kts)
          NEW_VERSION=$(echo "$CURRENT_VERSION" | awk -F. '{$NF=$NF+1; OFS=FS}1' | tr ' ' '.')
          COMMIT_HASH=$(git rev-parse --short HEAD)
          NEW_VERSION_WITH_HASH="$NEW_VERSION+$COMMIT_HASH"
          sed -i "s/version = \".*\"/version = \"$NEW_VERSION_WITH_HASH\"/" build.gradle.kts
          echo "version=$NEW_VERSION_WITH_HASH" >> $GITHUB_OUTPUT

      - name: Commit changes
        run: |
          export CONTENT="$(base64 -w 0 build.gradle.kts)"
          export SHA="$(git rev-parse ${{ steps.extract_branch.outputs.branch }}:build.gradle.kts)"
          echo "$CONTENT -- $SHA"
