name: Increment build-version

on:
  pull_request:
    branches: [ develop ]

jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ssh-key: ${{ secrets.DEPLOY_KEY }}

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "<>"

      - name: Extract branch name
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT
        id: extract_branch

      - name: Pull repository
        run: git fetch origin ${{ steps.extract_branch.outputs.branch }}

      - name: Bump Version
        run: |
          current_version=$(grep -oP '(?<=version = ").*(?=")' build.gradle.kts)
          new_version=$(echo "$current_version" | awk -F. '{$NF=$NF+1; OFS=FS}1' | tr ' ' '.')
          commit_hash=$(git rev-parse --short HEAD)
          new_version_with_hash="$new_version+$commit_hash"
          sed -i "s/version = \".*\"/version = \"$new_version_with_hash\"/" build.gradle.kts

      - name: Commit changes
        env:
          GH_TOKEN: ${{ github.token }}
        run: |
          export TODAY=$( date -u '+%Y-%m-%d' )
          export MESSAGE="chore: regenerate build.gradle.kts for $TODAY"
          export SHA=$( git rev-parse develop:build.gradle.kts )
          export CONTENT=$( base64 -i build.gradle.kts )
          gh api --method PUT /repos/:MerryDev/:Demo/contents/build.gradle.kts \
          --field message="$MESSAGE" \
          --field content="$CONTENT" \
          --field encoding="base64" \
          --field branch="$DESTINATION_BRANCH" \
          --field sha="$SHA"
