name: Increment build-version

on:
  pull_request:
    branches: [ develop ]

jobs:
  update-version:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          ssh-key: ${{ secrets.DEPLOY_KEY }}

      - name: Configure Git
        run: |
          git config --global user.name "GitHub Actions"
          git config --global user.email "<>"

      - name: Extract branch name
        id: extract_branch
        shell: bash
        run: echo "branch=${GITHUB_HEAD_REF:-${GITHUB_REF#refs/heads/}}" >> $GITHUB_OUTPUT

      - name: Pull repository
        run: git fetch origin ${{ steps.extract_branch.outputs.branch }}

      - name: Bump Version
        id: bump_version
        run: |
          CURRENT_VERSION=$(grep -oP '(?<=version = ").*(?=")' build.gradle.kts)
          NEW_VERSION=$(echo "$CURRENT_VERSION" | awk -F. '{$NF=$NF+1; OFS=FS}1' | tr ' ' '.')
          COMMIT_HASH=$(git rev-parse --short HEAD)
          NEW_VERSION_WITH_HASH="$NEW_VERSION+$COMMIT_HASH"
          sed -i "s/version = \".*\"/version = \"$NEW_VERSION_WITH_HASH\"/" build.gradle.kts
          echo "version=$NEW_VERSION_WITH_HASH" >> $GITHUB_OUTPUT

      - name: Commit changes
        shell: bash
        run: |
          curl -L \
          -X PUT \
          -H "Accept: application/vnd.github+json" \
          -H "Authorization: Bearer ${{ github.token }}" \
          -H "X-GitHub-Api-Version: 2022-11-28" \
          https://api.github.com/repos/MerryDev/Demo/contents/build.gradle.kts \
          -d '{"message":"Bump version to ${{ steps.bump_version.outputs.version }}","committer":{"name":"QuantraxNET","email":"github@quantrax.net"},"content":"$( base64 -i build.gradle.kts )","sha":"$( git rev-parse develop:build.gradle.kts)"}'
